#!/usr/bin/env bash
# Function to display usage message
usage() {
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}


# Assign arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Check if enough arguments are provided
if [ $# -lt 4 ]; then
  usage
  exit 1
esle
  scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:/home/ubuntu"
  exit 0
fi
