#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html


echo "Page Not Found" > 404.html
sudo mv 404.html /var/www/html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 www.linkedin.com/in/hany-aly-communication-machinelearning-engineer;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
