#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt -y update
sudo apt install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 474376-web-01 34.234.201.238:80 check
   server 474376-web-02 54.237.54.236:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
