#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.

counter=1
while [[ $counter -le 10 ]]; do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
