#!/usr/bin/env bash
# Bash script that displays Best School 10 times

counter=1
while [[ $counter -le 10 ]]; do
  if [[ $counter -eq 10 ]]; then
    echo "Hi"
  fi
  echo "Best School"
  ((counter++))
done
