#!/usr/bin/env bash
# Bash script that displays Best School 10 times

counter=1
while [[ $counter -le 10 ]]; do
  if [[ $counter -eq 4 ]]; then
    echo "bad luck"
  elif [[ $counter -eq 8 ]]; then
    echo "good luck"
  fi
  echo "Best School"
  ((counter++))
done
