#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

desired_entries=(
  "127.0.0.2 localhost"
  "8.8.8.8 facebook.com"
)
cp /etc/hosts /etc/hosts.bak
temp_file=$(mktemp)
for entry in "${desired_entries[@]}"; do
  echo "$entry" >> "$temp_file"
done
mv "$temp_file" /etc/hosts 
