#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.


cp /etc/hosts ~/hosts.bak
echo "127.0.0.2		localhost" > ~/hosts.bak
echo "8.8.8.8		facebook.com" >> ~/hosts.bak
cp -f ~/hosts.bak /etc/hosts
